import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { cn } from '@/lib/utils';
import './globals.css';
import QueryProvider from '@/components/query-provider';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
          <body className={cn(inter.className, 'antialiased min-h-screen')}>
              <NuqsAdapter>
                  <QueryProvider>
                      <Toaster visibleToasts={3} closeButton />
                      {children}
                  </QueryProvider>
              </NuqsAdapter>
          </body>
      </html>
  );
}
